POST http://localhost:3000
Content-Type: application/json; charset=UTF-8

{
    "name": "iamtk"
}

###
POST http://localhost:3000
Content-Type: application/x-www-form-urlencoded; charset=UTF-8

name=tae kwan&job=developer

###
POST http://localhost:3000
Content-Type: text/plain; charset=UTF-8

message test